[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anki-scraper"
version = "1.0.0"

[project.scripts]
anki-scraper = "anki_scraper.cli:app"

[tool.setuptools.packages.find]
where = ["."]

[tool.anki-scraper]
output_dir="./generated_decks"